### ISSUE TITLE
"apply" script does not handle errors correctly

### ISSUE THREAD

**Issue by basil** [delphix/delphix-platform#44] opened 2019-01-29 00:29 UTC
The `apply_playbook` function contains logic that attempts to fail the script with `exit 1` when `ansible-playbook` fails:

```bash
function apply_playbook() {
	if ! ansible-playbook -vvv \
		-c "$DLPX_ANSIBLE_CONNECTION" \
		-i "$DLPX_ANSIBLE_INVENTORY" \
		-e "root_filesystem=${ROOT_FILESYSTEM}" \
		"$1"; then
		echo "Failure when applying playbook." 2>&1
		exit 1
	fi
}
```

However, `apply_playbook` is invoked as follows:

```bash
find_playbooks | while read -r playbook; do
        apply_playbook "$playbook"
done
```

This spawns a sub-shell for the body of the loop, meaning that `exit 1` exits the subshell with a non-zero exit status rather than the higher-level shell (i.e., the one running `apply`). As such, the higher-level shell running `apply` drives on and exits cleanly, even though an error occurred.

A suggested fix is to switch to process substitution, as follows:

```bash
while read -r playbook; do
        apply_playbook "$playbook"
done < <(find_playbooks)
```

This avoids the subshell. Note that from the perspective of the invoked process, `<(...)` resolves to a named pipe, as this demonstrates:

```bash
$ echo <(true)
/dev/fd/63
```

**Comment by basil** [comment] 2019-01-29 00:55
bq. This spawns a sub-shell for the body of the loop, meaning that exit 1 exits the subshell with a non-zero exit status rather than the higher-level shell (i.e., the one running apply).

After running a few more experiments, I don't think this is actually the case. `exit 1` should still work in the presence of a subshell, as this example demonstrates:

```bash
printf "1\n2\n3\n" | while read foo; do
	echo "$foo"
	exit 1
done
```

As such I think my original analysis is wrong.

**Comment by prakashsurya** [comment] 2019-01-29 00:57
Is this a duplicate of https://github.com/delphix/appliance-build/issues/215? @jgallag88 is proposing a fix here: https://github.com/delphix/delphix-platform/pull/45.

**Comment by basil** [comment] 2019-01-29 00:59
Yeah, I think it is a duplicate.

**Comment by prakashsurya** [comment] 2020-03-24 16:45
Closing, as I believe this is fixed.

**Closed by prakashsurya** 2020-03-24 16:45 UTC
